COMPONENT=RadioLedsAppC
#BUILD_EXTRA_DEPS = RadioCountMsg.py RadioCountMsg.class
#CLEAN_EXTRA = RadioCountMsg.py RadioCountMsg.class RadioCountMsg.java

#RadioCountMsg.py: RadioLeds.h
#	mig python -target=$(PLATFORM) $(CFLAGS) -python-classname=RadioCountMsg RadioLeds.h radio_msg -o $@

#RadioCountMsg.class: RadioCountMsg.java
#	javac RadioCountMsg.java

#RadioCountMsg.java: RadioCountToLeds.h
#	mig java -target=$(PLATFORM) $(CFLAGS) -java-classname=RadioCountMsg RadioCountToLeds.h radio_count_msg -o $@


include $(MAKERULES)

